app = 'enhanced-customer-tracking'
primary_region = 'sjc'

[build]

[env]
  PORT = "8080"
  PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

