app = 'enhanced-customer-tracking'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  FLASK_ENV = "production"

